### ISSUE TITLE
sri4node crashes on non-existing param in url

### ISSUE THREAD

**Issue by stefanvds1** [katholiek-onderwijs-vlaanderen/sri4node#130]
RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:195:11)
    at ServerResponse.writeHead (/home/ubuntu/workspace/GIT/mail-api/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:159:8)
    at ServerResponse.end (/home/ubuntu/workspace/GIT/mail-api/node_modules/sri4node/node_modules/compression/index.js:103:14)
    at ServerResponse.send (/home/ubuntu/workspace/GIT/mail-api/node_modules/express/lib/response.js:204:10)
    at ServerResponse.json (/home/ubuntu/workspace/GIT/mail-api/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send (/home/ubuntu/workspace/GIT/mail-api/node_modules/express/lib/response.js:151:21)
    **at /home/ubuntu/workspace/GIT/mail-api/node_modules/sri4node/sri4node.js:187:50**
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by jgovaerts** [comment]
Not reproducible in v2.0
