### ISSUE TITLE
sriConfig without plugin crashes sri4node

### ISSUE THREAD

**Issue by stefanvds1** [katholiek-onderwijs-vlaanderen/sri4node#133]
if  'plugins' is not specified in the config, sri4node doesn't run

___________________________ SRI4NODE INITIALIZATION ERROR _____________________________
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Promise (/home/ubuntu/workspace/GIT/events-api/node_modules/p-map/index.js:18:27)
    at module.exports (/home/ubuntu/workspace/GIT/events-api/node_modules/p-map/index.js:2:46)
    at Object.configure (/home/ubuntu/workspace/GIT/events-api/node_modules/sri4node/sri4node.js:253:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by jgovaerts** [comment]
fixed in sprint-169-0
